version: '2'

services:
      web:
            build: .
            ports:
                - 48016:8080
            stdin_open: true
            tty: true
            volumes:
                - ./src:/var/www/html
                - ./logs:/var/log/apache2
