version: '3.5'

services:
    web:
        build: .
        volumes:
          - ./src/:/src/:ro
          - ./start.sh:/start.sh:ro
          - ./flag:/macao/fl3g_1s_th1s_Good_j0b:ro
          - ./nginx.conf:/etc/nginx/sites-available/default:ro
        ports:
          - 48024:80
